[package]
name = "lmm-logic-exec-verfy"
version = "0.1.0"
edition = "2021"

[dependencies]

serde_json = "1.0.108"
serde = { version = "1.0.192", features = ["derive"] }
reqwest = {version = "0.11.22", features = ["blocking", "json"]}
rand = "0.9.0-alpha.2"
